global:
  dockerRegistry:
    url: ghcr.io/nationalsecurityagency
  volumes:
    certificates:
      name: certificates
      destination: /data/certs
  initialization:
    image:
      name: busybox
      tag: 1.28
  certSecretName: certificates-secret
  pullSecrets:
    - dockerconfigjson-ghcr
  serviceDns:
    configuration:
      name: configuration
      port: 8888
    authorization:
      name: authorization
    cache:
      name: cache
      port: 8080


#######################################
# Default Values for Audit Deployment #
#######################################
image:
  name: datawave-audit-service
  pullPolicy: IfNotPresent
  tag: 4.0.2
livenessProbe:
  delaySeconds: 60
  periodSeconds: 5
  port: 8080
  scheme: HTTP
  uri: audit/mgmt/health
meta:
  name: audit
service:
  name: audit-service
readinessProbe:
  delaySeconds: 60
  periodSeconds: 5
  port: 8080
  scheme: HTTP
  uri: audit/mgmt/health
replication:
  maxSurge: 2
  maxUnavailable: 1
  replicaCount: 1
  revisionHistoryLimit: 10
restartPolicy: Always
  
####################################
# Default Values for Audit Service #
####################################

ports:
  http: 8080
  https: 8443
