global:
  volumes:
    hadoop_bootstrap:
      name: hadoop
      destination: /tmp/hadoop-config
      readOnly: true
      source:
        type: configmap
        name: hadoop-config
        create: true
config:
  coreSiteProperties:
    - name: fs.defaultFS
      value: "hdfs://hdfs-nn:9000/"
      description: NameNode URI

  hdfsSiteProperties:
    - name: hadoop.user.group.static.mapping.overrides
      value: datawave=hadoop;accumulo=hadoop
    - name: dfs.permissions.superusergroup
      value: "hadoop"
      description: Hadoop Super User Group
    - name: dfs.webhdfs.enabled
      value: "false"
      description: whether to start webhdfs
    - name: dfs.datanode.use.datanode.hostname
      value: "false"
      description: Use hostname for datanode
    - name: dfs.client.use.datanode.hostname
      value: "false"
      description: Use hostname for datanode from client
    - name: dfs.replication
      value: "3"
      description: Default Replication
    - name: dfs.datanode.data.dir
      value: "file:///usr/local/hadoop/hdfs/datanode"
      description: Datanode Data Directory
    - name: dfs.namenode.name.dir
      value: "file:///usr/local/hadoop/data"
      description: NameNode directory for namespace and transaction logs storage.
    - name: dfs.namenode.datanode.registration.ip-hostname-check
      value: "false"
      description: Disable hostname ip check
    - name: dfs.namenode.rpc-bind-host
      value: "0.0.0.0"
      description: Bind Namenode to all hosts
    - name: dfs.namenode.servicerpc-bind-host
      value: "0.0.0.0"
      description: Bind Namenode to all hosts
    - name: dfs.datanode.fileio.profiling.sampling.percentage
      value: "20"
      description: "Percentage of disk io to profile"

  mapredSiteProperties:
    - name: mapreduce.framework.name
      value: "yarn"
      description: What Framework to use
    - name: mapreduce.map.memory.mb
      value: "4096"
      description: "Default max task size"
    - name: mapreduce.jobhistory.address
      value: "yarn-rm:10020"
      description: Resource Manager Address
    - name: mapreduce.jobhistory.webapp.address
      value: "0.0.0.0:19888"
      description: Bind RM to all hosts

  yarnSiteProperties:
    - name: yarn.resourcemanager.hostname
      value: "yarn-rm"
      description: Resource Manager dns name
    - name: yarn.resourcemanager.bind-host
      value: "0.0.0.0"
      description: Bind RM to all interfaces
    - name: yarn.nodemanager.bind-host
      value: "0.0.0.0"
      description: Bind NM to all interfaces
    - name: yarn.timeline-service.bind-host
      value: "0.0.0.0"
      description: Bind TS to all interfaces
    - name: yarn.nodemanager.vmem-check-enabled
      value: "false"
      description: Disable VMEM Check
    - name: yarn.nodemanager.aux-services
      value: "mapreduce_shuffle"
      description: Node Manager Auxiliary Services
    - name: yarn.nodemanager.aux-services.mapreduce_shuffle.class
      value: "org.apache.hadoop.mapred.ShuffleHandler"
      description: Class to use for mapreduce_shuffle
    - name: yarn.nodemanager.resource.memory-mb
      value: "4096"
      description: Memory size for each node manager
    - name: yarn.nodemanager.local-dirs
      value: "/opt/hdfs/hadoop-yarn/cache/${user.name}/nm-local-dir"
      description: Nodemanager local directory
    - name: yarn.nodemanager.log-dirs
      value: "/opt/hdfs/hadoop-yarn/containers"
      description: Nodemanager local logs directory
    - name: yarn.nodemanager.remote-app-log-dir
      value: "/opt/hdfs/hadoop-yarn/contaiappsners"
      description: Nodemanager log aggregation directory
    - name: yarn.resourcemanager.scheduler.class
      value: "org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler"
      description: Scheduler Class to use
    - name: yarn.application.classpath
      value: "/usr/local/hadoop/conf,/usr/lib/hadoop/*,/usr/lib/hadoop/lib/*,/usr/lib/hadoop-hdfs/*,/usr/lib/hadoop-hdfs/lib/*,/usr/lib/hadoop-yarn/*,/usr/lib/hadoop-yarn/lib/*,/usr/lib/hadoop-yarn/timelineservice/*,/usr/lib/hadoop-mapreduce/*,"
      description: Classpath for Yarn jobs