# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accumulo.fullname" . }}-manager
  labels:
    {{- include "accumulo.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "accumulo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "accumulo.labels" . | nindent 8 }}
        app.kubernetes.io/component: manager
    spec:
      securityContext:
        runAsUser: 1001
      initContainers:
      - name: check-hadoop-jars
        image: "{{ .Values.initContainer.image }}:{{ .Values.initContainer.tag }}"
        securityContext:
          runAsUser: 1000
        command: 
        - "/bin/sh"
        args: ["-c", "while [ `hdfs dfs -ls hdfs://hdfs-nn:9000/datawave/accumulo-vfs-classpath | wc -l` -lt 5 ]; do echo \"Waiting for jars to load\"; sleep 10; done"]
      hostname: accumulo-manager 
      containers:
      - name: accumulo-manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args: ["./entrypoint.sh accumulo manager -a $(hostname -f)" ]
        ports:
          - containerPort: 9999
        env:
        - name: HADOOP_CONF_DIR
          value: /usr/local/hadoop/conf
        - name: ACCUMULO_CONF_DIR
          value: {{ .Values.config.path }}
        - name: ACCUMULO_INSTANCE_NAME
          value: {{ .Values.instanceId }}
        - name: HADOOP_CLASSPATH
          value: {{ .Values.hadoop.classpath }}
        - name: ACCUMULO_ROOT_PASSWORD
          value: {{ .Values.config.userManagement.rootPassword }}
        volumeMounts:
          - name: hadoop-config
            mountPath: /usr/local/hadoop/conf
          - name: config
            mountPath: /opt/accumulo/conf
          - name: cmds
            mountPath: /cmds
            readOnly: true
        resources:
          {{- toYaml .Values.manager.resources | nindent 10 }}
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ .Values.hadoopConfigMap }}
        - name: config
          configMap:
            name: accumulo-config
        - name: cmds
          secret:
            secretName: {{ include "accumulo.fullname" . }}-cmds
            optional: false
      {{- with .Values.manager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
