global:
  volumes:
    rabbitmq:
      name: rabbitmq
      destination: /etc/rabbitmq
##########################################
# Default Values for RabbitMQ Deployment #
##########################################
tolerations: []
rabbitmqDeployment:
  image:
    name: rabbitmq
    pullPolicy: IfNotPresent
    tag: 3.11.4-alpine
  meta:
    name: rabbitmq
  replication:
    maxSurge: 2
    maxUnavailable: 1
    replicaCount: 1
    revisionHistoryLimit: 10
  restartPolicy: Always
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1
###################################
# Default Values for RabbitMQ Map #
###################################

rabbitmqConfigmap:
  meta:
    name: rabbitmq-map

#######################################
# Default Values for RabbitMQ Service #
#######################################

rabbitmqService:
  meta:
    name: rabbitmq
  ports:
    amqp: 5672
    mgmt: 15672


########################################
# Default Values for RabbitMQ Volumes  #
########################################


