######################################
# Default Values for Docker Registry #
######################################
global:
  dockerRegistry:
    url: ""
charts:
  zookeeper:
    enabled: true
  hadoop:
    enabled: true
external:
  zookeeper:
    hosts:
      - zookeeper
  hdfs:
    hosts:
      - hdfs-nn
      - hdfs-dn
  yarn:
    hosts:
      - yarn-rm
      - yarn-nm

dwv-hadoop:
  persistence:
    nameNode:
      enabled: true
      definitions:
        - metadata:
            name: dfs
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-hostpath-sc"
            resources:
              requests:
                storage: 5Gi
            selector:
    dataNode:
      enabled: true
      definitions:
        - metadata:
            name: dfs
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-hostpath-sc"
            resources:
              requests:
                storage: 5Gi
            selector:
dwv-zookeeper:
  persistence:
    enabled: true