# Source: helm-lib/templates/deployment.yaml
{{- define "common-service-library.deployment.tpl" -}}

####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.meta.name }}"
  labels:
    application: "{{ .Values.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.replication.maxSurge }}
      maxUnavailable: {{ .Values.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Values.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Values.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: "{{ .Values.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################
      securityContext:
        runAsUser: 1000
      containers:
        - name: "{{ .Values.meta.name }}"
          args:
          {{- range $i, $value := .Values.args }}
          - {{ $value }}
          {{- end }}
          env:
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Values.global.serviceDns.configuration.name }}:{{ .Values.global.serviceDns.configuration.port }}/configserver"
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.uri }}"
              port: {{ .Values.livenessProbe.port }}
              scheme: "{{ .Values.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}            
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.uri }}"
              port: {{ .Values.readinessProbe.port }}
              scheme: "{{ .Values.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          ports:
          {{- range $i, $value := .Values.ports }}
            - containerPort: {{ $value }}
          {{- end }}
          resources: {}
          volumeMounts:
            - name: "{{ .Values.global.volumes.certificates.name }}"
              mountPath: "{{ .Values.global.volumes.certificates.destination }}"
              readOnly: true

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers: {}

      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: "{{ .Values.global.volumes.certificates.name }}"
          secret:
            secretName: {{ .Values.global.certSecretName}}
            optional: false
{{- end -}}
{{- define "common-service-library.deployment" -}}
{{- include "common-service-library.util.merge" (append . "common-service-library.deployment.tpl") -}}
{{- end -}}

