# Source: helm-lib/templates/deployment.yaml
{{- define "common-service-library.deployment.tpl" -}}

####################################
# Core Helm Template Configuration #
####################################

apiVersion: apps/v1
kind: Deployment

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  name: "{{ .Values.meta.name }}"
  labels:
    application: "{{ .Values.meta.name }}"

#####################################
# Complete Deployment Specification #
#####################################

spec:

  ######################################
  # Replication / Update Configuration #
  ######################################

  replicas: {{ .Values.replication.replicaCount }}
  revisionHistoryLimit: {{ .Values.replication.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.replication.maxSurge }}
      maxUnavailable: {{ .Values.replication.maxUnavailable }}

  ###################################
  # Resource Selector Configuration #
  ###################################

  selector:
    matchLabels:
      application: "{{ .Values.meta.name }}"
  
  #####################################
  # Deployment Template Configuration #
  #####################################

  template:

    ##################################################
    # Basic Metadata for this Deployment's Resources #
    ##################################################

    metadata:
      labels:
        application: "{{ .Values.meta.name }}"

    #######################################
    # Deployment Resources Specifications #
    #######################################

    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: "{{ .Values.restartPolicy }}"

      ##############################################
      # Containers Associated with this Deployment #
      ##############################################
      securityContext:
        runAsUser: 1000
      containers:
        - name: "{{ .Values.meta.name }}"
          args:
            - "--spring.output.ansi.enabled=ALWAYS"
            - "--spring.profiles.active={{ .Values.profiles }}"
          env:
            - name: CONFIG_SERVER_URL
              value: "http://{{ .Values.global.serviceDns.configuration.name }}:{{ .Values.global.serviceDns.configuration.port }}/configserver"
          image: "{{ .Values.global.dockerRegistry.url }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.uri }}"
              port: {{ .Values.livenessProbe.port }}
              scheme: "{{ .Values.livenessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.livenessProbe.delaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.uri }}"
              port: {{ .Values.readinessProbe.port }}
              scheme: "{{ .Values.readinessProbe.scheme }}"
            initialDelaySeconds: {{ .Values.readinessProbe.delaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - name: "{{ .Values.global.volumes.certificates.name }}"
              mountPath: "{{ .Values.global.volumes.certificates.destination }}"
              readOnly: true

      #############################################################
      # Initialization Containers Associated with this Deployment #
      #############################################################

      initContainers:

        - name: "{{ .Chart.Name }}-init-authorization"
          image: "{{ .Values.global.initialization.image.name }}:{{ .Values.global.initialization.image.tag }}"
          command: [ "sh", "-c", "until nc -z {{ .Values.global.serviceDns.authorization.name }} {{ .Values.global.serviceDns.authorization.port }}; do echo 'Waiting for Authorization...'; sleep 2; done" ]
        
        - name: "{{ .Chart.Name }}-init-cache"
          image: "{{ .Values.global.initialization.image.name }}:{{ .Values.global.initialization.image.tag }}"
          command: [ "sh", "-c", "until nc -z {{ .Values.global.serviceDns.cache.name }} {{ .Values.global.serviceDns.cache.port }}; do echo 'Waiting for Cache...'; sleep 2; done" ]

        - name: "{{ .Chart.Name }}-init-configuration"
          image: "{{ .Values.global.initialization.image.name }}:{{ .Values.global.initialization.image.tag }}"
          command: [ "sh", "-c", "until nc -z {{ .Values.global.serviceDns.configuration.name }} {{ .Values.global.serviceDns.configuration.port }}; do echo 'Waiting for Configuration...'; sleep 2; done" ]
      
      ###########################################
      # Volumes Associated with this Deployment #
      ###########################################

      volumes:
        - name: "{{ .Values.global.volumes.certificates.name }}"
          secret:
            secretName: {{ .Values.global.certSecretName}}
            optional: false
{{- end -}}
{{- define "common-service-library.deployment" -}}
{{- include "common-service-library.util.merge" (append . "common-service-library.deployment.tpl") -}}
{{- end -}}

